### ISSUE TITLE
Trading fees

### ISSUE THREAD

**Issue by ArnaudCarrere** [bilaxy-exchange/bilaxy-api-docs#5]
Hi,
Can you please add fees for each trade of the response of /v1/accounts/trades ?
Thanks

**Comment by BilaxyTech** [comment]
@ArnaudCarrere 
This feature is scheduled to be added within the week.

**Comment by ArnaudCarrere** [comment]
Hi,
Regarding the pull request you merged earlier today, the example in restapi.md is ambiguous. The "fees_currency" field is "BIA" for both buy and sell BIA-ETH orders. What is the general rule for "fees_currency" ? Is it always the ticker asset (BIA in our case), or does it depend on the side like most exchanges do (BIA if you buy, ETH if you sell in our case) ?
Thanks
