### ISSUE TITLE
About signature sha256

### ISSUE THREAD

**Issue by Kahen** [bilaxy-exchange/bilaxy-api-docs#9]
signature use secret as key , and all params as the value for the HMAC operation. it means other params? for example ,account balance, use timestamp and appkey as value? 
another question, i don't know the values formation. can i follows old api,use appkey and timestamp as params,then join with '&' and finally encrpted with sha256?

**Comment by theHour** [comment]
Hey @Kahen did you found out how to create a signature?
Its not really clear from the documentation,

**Comment by Kahen** [comment]
> Hey @Kahen did you found out how to create a signature?
> Its not really clear from the documentation,

I clear know. firstly, you should build a sortable TreeMap with params,(for example,if you want to get info,your params should contain apikey and timestamp.
and build the query String

```java
StringBuilder result = new StringBuilder();
        boolean first = true;
        for (Map.Entry<String, Object> entry : params.entrySet()) {
            if (first) {
                first = false;
            } else {
                result.append("&");
            }
            result.append(entry.getKey());
            result.append("=");
            result.append(encodeURIComponent(entry.getValue().toString()));
        }

        return result.toString();
    }
```

after that,you can build signature with HMac256 by query String.Finally,put the sign to the params map, you also can add to header, then sent request

**Comment by BilaxyTech** [comment]
@Kahen 

There are 3 steps to create a signature,
1. sorted params by keys
2. urlencode params
3. hmac_sha256

Sorting is missing in your code.

**Comment by Maddest** [comment]
Hey @Kahen,

could you please post an example string for '1. sorted params by keys' and '2. urlencode params'? I still get errors when doing this. Thanks in advance :-)

**Comment by arch0x** [comment]
@Maddest 

please check demo: https://github.com/bilaxy-exchange/bilaxy-api-docs/blob/f00b5f889ff8373b35f00d966866f953f17d2825/py_simple_sdk.py#L18

**Comment by Maddest** [comment]
@wjdnsdhydl 

Thanks a lot, that solved my problem :-)
